### ISSUE TITLE
Size isn't printed in hex

### ISSUE THREAD

**Issue by MrOneTwo** [mastupristi/memoryLayout#1]
Nice tool!

I think there might be an issue here. You use a `size(hex)` header but you actually print the size in dec. Seems like it should be `%x`?
https://github.com/mastupristi/memoryLayout/blob/f9e560bb96585fa6a1cbe29f697cb1021f3c680c/dissect.py#L93

**Comment by mastupristi** [comment]
> Nice tool!

thank you

I actually wanted the size to be in decimal, so I have to change the label

([3dba8e851ac75d3b1f55dc8be5946b22032aa6ac](https://github.com/mastupristi/memoryLayout/tree/3dba8e851ac75d3b1f55dc8be5946b22032aa6ac))
